"""The installable-app surface: manifest, service worker, offline answer.

This is the PWA route recommended over a native Android build when the
question came up: with these three pieces served, Chrome on Android offers
"Add to Home screen" as a real install (standalone window, launcher icon,
app switcher entry), and iOS Safari honors the same manifest. No store, no
second codebase, no release process beyond the site's own deploy.

The service worker is minimal ON PURPOSE, and the reason is this app's shape.
A Dash page is its layout plus live callbacks: a service worker that cached
the shell or the data endpoints would serve stale layouts with total
confidence, which is the exact failure the app's cache policy exists to
prevent (no-store on the dash endpoints, no-cache on HTML). So there is no
Cache Storage here at all. The fetch handler exists because installability
wants one, and the only behaviour it adds is an honest offline page for
navigations; everything else passes straight through to the network and the
HTTP cache, whose rules routing.cache_policy already states.

Icons live in src/assets (generated by scripts/make_pwa_icons.py, their
reproducer); the manifest and worker are served from the ROOT by app_cot
routes, because a service worker's scope cannot exceed its own path and a
worker under /assets/ could only control /assets/.
"""
import json

#: One color, three places: the manifest's theme/background, the meta tag in
#: the index template, and the icons' ground (scripts/make_pwa_icons.py).
THEME_COLOR = "#1a1a1a"

MANIFEST = {
    "name": "COT Analyzer",
    "short_name": "COT Analyzer",
    "description": ("Free weekly Commitments of Traders charts and signals "
                    "for 40+ futures markets."),
    "id": "/",
    "start_url": "/",
    "scope": "/",
    "display": "standalone",
    "background_color": THEME_COLOR,
    "theme_color": THEME_COLOR,
    "icons": [
        {"src": "/assets/icon-192.png", "sizes": "192x192",
         "type": "image/png"},
        {"src": "/assets/icon-512.png", "sizes": "512x512",
         "type": "image/png"},
        {"src": "/assets/icon-maskable-512.png", "sizes": "512x512",
         "type": "image/png", "purpose": "maskable"},
    ],
}


def manifest_json():
    return json.dumps(MANIFEST, indent=2)


_OFFLINE_PAGE = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Offline | COT Analyzer</title>
<style>
  body {{ background:{THEME_COLOR}; color:#ABB8C9;
         font-family:system-ui,-apple-system,"Segoe UI",sans-serif;
         display:flex; align-items:center; justify-content:center;
         height:100vh; margin:0; text-align:center; }}
  h1 {{ color:#e8eef5; font-size:1.3rem; margin:0 0 .5rem; }}
  p  {{ margin:0; font-size:.9rem; }}
</style></head>
<body><div>
  <h1>You are offline</h1>
  <p>COT Analyzer needs a connection: every chart is live data.</p>
</div></body></html>"""

SERVICE_WORKER = """// Minimal on purpose; see src/pwa.py for the argument.
// No Cache Storage: a cached Dash shell is a stale app served with total
// confidence. Installability wants a fetch handler, so the one behaviour
// here is an honest offline page for navigations; everything else passes
// straight through to the network and the HTTP cache.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

const OFFLINE_PAGE = __OFFLINE_PAGE__;

self.addEventListener('fetch', (event) => {
    if (event.request.mode !== 'navigate') { return; }
    event.respondWith(fetch(event.request).catch(() => new Response(
        OFFLINE_PAGE,
        {status: 503, headers: {'Content-Type': 'text/html; charset=utf-8'}}
    )));
});
""".replace('__OFFLINE_PAGE__', json.dumps(_OFFLINE_PAGE))
